/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=apps/worker/poc/oq-002/wrangler.jsonc --include-runtime=false --strict-vars=false --env-interface=Oq002Bindings apps/worker/poc/oq-002/worker-configuration.d.ts` (hash: 0b74d39db4e2da42d6f1acc85b706c15)
interface __BaseEnv_Oq002Bindings {
	SUPABASE_URL: string;
	SUPABASE_PUBLISHABLE_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_Oq002Bindings {}
}
interface Oq002Bindings extends __BaseEnv_Oq002Bindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "SUPABASE_URL" | "SUPABASE_PUBLISHABLE_KEY">> {}
}
